### ISSUE TITLE
Failed to activate the build-tools-make package

### ISSUE THREAD

**Issue by Idil77soltakhanov** [deprint/build-tools-make#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [build-tools-make](https://github.com/deprint/build-tools-make) package 0.2.1

### Stack Trace

Failed to activate the build-tools-make package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.38.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:155156)
    at Module.require (/app.asar/static/index.js:53:43)
    at require (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:146462)
    at /packages/build-tools-make/lib/module.coffee:5:26)
    at /packages/build-tools-make/lib/module.coffee:1:1)
    at /packages/build-tools-make/lib/module.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:147172)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:146462)
    at Object.provideProvider (/packages/build-tools-make/lib/build-tools-make.coffee:5:10)
    at Package.activateServices (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3542128)
    at Package.activateNow (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3539249)
    at measure (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3538573)
    at Package.measure (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3536204)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3538433)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3538376)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:381112)
    at config.transactAsync (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:380728)
    at Config.transactAsync (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:330844)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:380678)
    at PackageManager.activate (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:380296)
    at t.loadState.then (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:1:710821)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
build-cmake 0.12.0 
build-tools 4.5.13 
build-tools-make 0.2.1 
cyber-theme-syntax 0.1.0 
gcc-make-run 0.2.12 
Hydrogen 2.10.2 
markdown-image-paste-delete 0.3.0 
my-theme-syntax 0.0.0 
script 3.18.1 
teletype 0.13.4 
```

**Comment by fstiewitz** [comment]
How did you install the package?
